Algoritmo "Operador_Relacional"

Var

 nome : caractere
 idade : caractere
 fruta : caractere
 resultado : caractere
 
 
Inicio

escreva("Qual seu nome: ")
 leia(nome)

 escreva(nome + " escreva sua idade: ")
 leia(idade)

 escreva(nome + " escreva sua fruta preferida: ")
 leia(fruta)


 resultado <- "Olá " + nome + ", sua idade é " + idade +", e sua fruta preferidade é " + fruta

escreva (resultado)




Fimalgoritmo