Algoritmo "exVetor02"

Var

n1, n2, n3 : vetor[0..4] de inteiro
cont : inteiro

Inicio

cont <- 0

para cont de 0 ate 4 faca
     escreva("Escreva um valor: ")
     leia(n1[cont])
     escreva("Escreva outro valor: ")
     leia(n2[cont])
fimpara


para cont de 0 ate 4 faca

     n3[cont] <- n1[cont] + n2[cont]
     escreval ("O valor da soma da posição", cont, " é: ", n3[cont])
fimpara





Fimalgoritmo